[package]
name = "psup"
version = "0.1.0"
authors = ["muji <muji@tmpfs.org>"]
edition = "2018"
default-run = "supervisor"
description = "Process supervisor using JSON-RPC over Unix sockets via tokio"
keywords = ["Process", "Supervisor", "JSON-RPC"]
repository = "https://github.com/tmpfs/tmpfs.org"
license = "MIT OR Apache-2.0"
readme = "README.md"

[dependencies]
thiserror = "1"
futures = "0.3"
rand = "0.8"
tokio = { version = "1", features = ["full"] }
json-rpc2 = { version= "0.9", features = ["async"] }
serde_json = "1"
serde = {version = "1", features = ["derive"]}
log = "0.4"
pretty_env_logger = "0.4"
once_cell = "1.7"
tokio-util = { version = "0.6", features = ["codec"] }
async-trait = "0.1"

[[bin]]
name = "supervisor"
path = "bin/supervisor.rs"

[[bin]]
name = "worker"
path = "bin/worker.rs"

[features]
default = ["supervisor", "worker"]
worker = []
supervisor = []
